@echo off
echo Starting SmartHR Backend...
cd backend
echo Starting backend JAR...
java -jar target\backend-0.0.1-SNAPSHOT.jar --spring.config.location=file:src/main/resources/application.properties --spring.jpa.hibernate.ddl-auto=update
pause
